/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto.TresPlataformas;

/**
 *
 * @author Sanele
 */
public class frmDesktop extends javax.swing.JFrame {

    /**
     * Creates new form frmDesktop
     */
    public frmDesktop() {
        initComponents();
    }
    clsDatabaseQueryingMethods clsQueryingMethods = new clsDatabaseQueryingMethods();
    
    private String strUserIdentifier;
    
    public String mGetUserIdentifier()
    {
        return strUserIdentifier;
    }
    public void mSetUserIdentifier(String strValue)
    {
        this.strUserIdentifier = strValue;
    }
    public void mUAC()
    {
        switch(strUserIdentifier)
        {
            case "GeneralUser":
                mnuFile.setVisible(true);
                mnueBooks.setVisible(true);
                mnuLibraryManagement.setVisible(false);
                mnuAccountManagement.setVisible(true);
                mnuAdminAccounts.setVisible(false);
                break;
            case "Admin":
                mnuFile.setVisible(true);
                mnueBooks.setVisible(true);
                mnuLibraryManagement.setVisible(true);
                mnuAccountManagement.setVisible(false);
                mnuAdminAccounts.setVisible(true);
                break;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsktpDesktop = new javax.swing.JDesktopPane();
        lblBackground = new javax.swing.JLabel();
        mnuBarTresPlataformas = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItemLogOff = new javax.swing.JMenuItem();
        mnuItemExit = new javax.swing.JMenuItem();
        mnuItemHelp = new javax.swing.JMenuItem();
        mnueBooks = new javax.swing.JMenu();
        mnuItemeLibrary = new javax.swing.JMenuItem();
        mnuLibraryManagement = new javax.swing.JMenu();
        mnuItemManageELibrary = new javax.swing.JMenuItem();
        mnuItemViewELibrary = new javax.swing.JMenuItem();
        mnuAccountManagement = new javax.swing.JMenu();
        mnuItemEditAccount = new javax.swing.JMenuItem();
        mnuItemDeleteAccount = new javax.swing.JMenuItem();
        mnuAdminAccounts = new javax.swing.JMenu();
        mnuItemManageAdminAccounts = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Developer's Konner :\\>");
        setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        setIconImages(null);

        dsktpDesktop.setBackground(new java.awt.Color(255, 255, 255));
        dsktpDesktop.setForeground(new java.awt.Color(255, 255, 255));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/TresPlataformas/Developer's Konner.png"))); // NOI18N

        dsktpDesktop.setLayer(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dsktpDesktopLayout = new javax.swing.GroupLayout(dsktpDesktop);
        dsktpDesktop.setLayout(dsktpDesktopLayout);
        dsktpDesktopLayout.setHorizontalGroup(
            dsktpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 984, Short.MAX_VALUE)
        );
        dsktpDesktopLayout.setVerticalGroup(
            dsktpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 632, Short.MAX_VALUE)
        );

        mnuFile.setText("File");
        mnuFile.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        mnuItemLogOff.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemLogOff.setText("Log Off");
        mnuItemLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogOffActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemLogOff);

        mnuItemExit.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemExit.setText("exit");
        mnuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemExit);

        mnuItemHelp.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemHelp.setText("Help");
        mnuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemHelpActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemHelp);

        mnuBarTresPlataformas.add(mnuFile);

        mnueBooks.setText("Programming e-books");
        mnueBooks.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        mnuItemeLibrary.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemeLibrary.setText("e-Library");
        mnuItemeLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemeLibraryActionPerformed(evt);
            }
        });
        mnueBooks.add(mnuItemeLibrary);

        mnuBarTresPlataformas.add(mnueBooks);

        mnuLibraryManagement.setText("Library Management");
        mnuLibraryManagement.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        mnuItemManageELibrary.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemManageELibrary.setText("Manage e-Library");
        mnuItemManageELibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemManageELibraryActionPerformed(evt);
            }
        });
        mnuLibraryManagement.add(mnuItemManageELibrary);

        mnuItemViewELibrary.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemViewELibrary.setText("View e-Library Books");
        mnuItemViewELibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViewELibraryActionPerformed(evt);
            }
        });
        mnuLibraryManagement.add(mnuItemViewELibrary);

        mnuBarTresPlataformas.add(mnuLibraryManagement);

        mnuAccountManagement.setText("Account Management");
        mnuAccountManagement.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        mnuItemEditAccount.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemEditAccount.setText("Edit account details");
        mnuItemEditAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEditAccountActionPerformed(evt);
            }
        });
        mnuAccountManagement.add(mnuItemEditAccount);

        mnuItemDeleteAccount.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemDeleteAccount.setText("Delete Account");
        mnuItemDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDeleteAccountActionPerformed(evt);
            }
        });
        mnuAccountManagement.add(mnuItemDeleteAccount);

        mnuBarTresPlataformas.add(mnuAccountManagement);

        mnuAdminAccounts.setText("Admin Accounts");
        mnuAdminAccounts.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        mnuItemManageAdminAccounts.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        mnuItemManageAdminAccounts.setText("Manage Admin Accounts");
        mnuItemManageAdminAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemManageAdminAccountsActionPerformed(evt);
            }
        });
        mnuAdminAccounts.add(mnuItemManageAdminAccounts);

        mnuBarTresPlataformas.add(mnuAdminAccounts);

        setJMenuBar(mnuBarTresPlataformas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDeleteAccountActionPerformed
        jifrmUpdateDetails jifrmU = new jifrmUpdateDetails();
        jifrmU.setLocation(500, 160);
        dsktpDesktop.add(jifrmU);
        jifrmU.setVisible(true);
        jifrmU.lblEditAccountDetails.setText("Delete Account");
        jifrmU.btnEdit.setText("Delete");
        jifrmU.btnSave.setText("Cancel");
    }//GEN-LAST:event_mnuItemDeleteAccountActionPerformed

    private void mnuItemEditAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEditAccountActionPerformed
        jifrmUpdateDetails jifrmU = new jifrmUpdateDetails();
        jifrmU.setLocation(500, 160);
        dsktpDesktop.add(jifrmU);
        jifrmU.setVisible(true);
    }//GEN-LAST:event_mnuItemEditAccountActionPerformed

    private void mnuItemLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogOffActionPerformed
        frmLogin frmlogin = new frmLogin();
        frmlogin.setVisible(true);
        frmlogin.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItemLogOffActionPerformed

    private void mnuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItemExitActionPerformed

    private void mnuItemeLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemeLibraryActionPerformed
        frmeLibrary frmeLibry = new frmeLibrary();
        frmeLibry.setVisible(true);
        frmeLibry.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItemeLibraryActionPerformed

    private void mnuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemHelpActionPerformed
        jifrmHelp jifrmhelp = new jifrmHelp();
        dsktpDesktop.add(jifrmhelp);
        jifrmhelp.setLocation(500, 160);
        jifrmhelp.setVisible(true);
        jifrmhelp.setSize(396, 308);
        
    }//GEN-LAST:event_mnuItemHelpActionPerformed

    private void mnuItemViewELibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViewELibraryActionPerformed
        jifrmLibraryManagement jifrmViewBooks = new jifrmLibraryManagement();
        clsQueryingMethods.mDisplayInTable(
                "SELECT BookISBN, BookTitle, Author, Category FROM tblBooks ORDER BY Category ASC",
                jifrmViewBooks);
        jifrmViewBooks.setLocation(500, 160);
        dsktpDesktop.add(jifrmViewBooks);
        jifrmViewBooks.setVisible(true);
    }//GEN-LAST:event_mnuItemViewELibraryActionPerformed

    private void mnuItemManageELibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemManageELibraryActionPerformed
        jifrmLibraryManagement jifrmLibrMgmt = new jifrmLibraryManagement();
        jifrmLibrMgmt.setLocation(500, 160);
        dsktpDesktop.add(jifrmLibrMgmt);
        jifrmLibrMgmt.show();
    }//GEN-LAST:event_mnuItemManageELibraryActionPerformed

    private void mnuItemManageAdminAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemManageAdminAccountsActionPerformed
        jifrmAdminAccountsManagement jifrmAdmins = new jifrmAdminAccountsManagement();
        jifrmAdmins.setLocation(500, 160);
        dsktpDesktop.add(jifrmAdmins);
        jifrmAdmins.setVisible(true);
    }//GEN-LAST:event_mnuItemManageAdminAccountsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dsktpDesktop;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JMenu mnuAccountManagement;
    private javax.swing.JMenu mnuAdminAccounts;
    private javax.swing.JMenuBar mnuBarTresPlataformas;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuItemDeleteAccount;
    private javax.swing.JMenuItem mnuItemEditAccount;
    private javax.swing.JMenuItem mnuItemExit;
    private javax.swing.JMenuItem mnuItemHelp;
    private javax.swing.JMenuItem mnuItemLogOff;
    private javax.swing.JMenuItem mnuItemManageAdminAccounts;
    private javax.swing.JMenuItem mnuItemManageELibrary;
    private javax.swing.JMenuItem mnuItemViewELibrary;
    private javax.swing.JMenuItem mnuItemeLibrary;
    private javax.swing.JMenu mnuLibraryManagement;
    private javax.swing.JMenu mnueBooks;
    // End of variables declaration//GEN-END:variables
}
