/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto.TresPlataformas;

import javax.swing.JOptionPane;

/**
 *
 * @author Sanele
 */
public class jifrmCreateAccount extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifrmCreateAccount
     */
    public jifrmCreateAccount() {
        initComponents();
        txtAccountName.requestFocusInWindow();
    }
    boolean boolAccountExist = false;
    clsDatabaseQueryingMethods clsQueryingMethods = new clsDatabaseQueryingMethods();
    clsIDGenerator id = new clsIDGenerator();
    
    private void mSaveAccountDetails()
    {
        if(txtAccountName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Account Name field cannot be left empty");
            txtAccountName.requestFocusInWindow();
        }
        else if(txtAccountPassword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Account Password field cannot be left empty");
            txtAccountPassword.requestFocusInWindow();
        }
        else{
            try{
                boolAccountExist = clsQueryingMethods.mCheckIfRecordExists("SELECT * FROM tblGeneralUsers WHERE AccountName='" + txtAccountName.getText().toLowerCase()
                                    +"' AND AccountPassword ='" + clsPasswordAESCryptography.mEncryptPassword(txtAccountPassword.getText())+"'");
            }catch(NullPointerException eX){
                JOptionPane.showMessageDialog(null, "Technical error encountered, try again.");
            }
            if(boolAccountExist == true)
            {
                boolAccountExist = false;
                JOptionPane.showMessageDialog(null, "You have an account already.");
            }
            else if(boolAccountExist == false)
            {
                clsQueryingMethods.mCreateRecord("INSERT INTO tblGeneralUsers " + "(AccountID, AccountName, AccountPassword)" + 
                        "VALUES ('"+id.mGetID().toString()+"','"+ txtAccountName.getText() + "','" + clsPasswordAESCryptography.mEncryptPassword(txtAccountPassword.getText().toLowerCase())+"')");
                JOptionPane.showMessageDialog(null, "Account has been created.");
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateAccount = new javax.swing.JLabel();
        lblAccountName = new javax.swing.JLabel();
        txtAccountName = new javax.swing.JTextField();
        lblAccountPassword = new javax.swing.JLabel();
        txtAccountPassword = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Create an account");
        setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/TresPlataformas/e-Library.jpg"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(379, 255));
        setMinimumSize(new java.awt.Dimension(379, 255));
        setPreferredSize(new java.awt.Dimension(379, 254));
        getContentPane().setLayout(null);

        lblCreateAccount.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateAccount.setText("Create an account");
        getContentPane().add(lblCreateAccount);
        lblCreateAccount.setBounds(100, 10, 190, 20);

        lblAccountName.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblAccountName.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountName.setText("Account name");
        getContentPane().add(lblAccountName);
        lblAccountName.setBounds(20, 60, 110, 17);

        txtAccountName.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        getContentPane().add(txtAccountName);
        txtAccountName.setBounds(230, 60, 110, 21);

        lblAccountPassword.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblAccountPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountPassword.setText("Account Password");
        getContentPane().add(lblAccountPassword);
        lblAccountPassword.setBounds(20, 110, 130, 17);
        getContentPane().add(txtAccountPassword);
        txtAccountPassword.setBounds(230, 110, 110, 20);

        btnCreate.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate);
        btnCreate.setBounds(30, 170, 100, 25);

        btnCancel.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(240, 170, 90, 25);

        lblBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanele\\Documents\\Information Technology\\Project_iii_Systems\\A\\Light-dots-with-blue-tech-background-vector-09.jpg")); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 400, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        mSaveAccountDetails();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblAccountName;
    private javax.swing.JLabel lblAccountPassword;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JTextField txtAccountName;
    private javax.swing.JTextField txtAccountPassword;
    // End of variables declaration//GEN-END:variables
}
